apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: springcloud
  namespace: default
spec:
  components:
    - name: config-server
      type: webservice
      properties:
        image: springcloud/configserver
        port: 8888
        livenessProbe:
          initialDelaySeconds: 120
          tcpSocket: 
            port: 8888
        redinessProbe:
          initialDelaySeconds: 60
          tcpSocket: 
            port: 8888
      traits:
        - type: expose
          properties:
            port: 8888
    - name: eureka-server
      type: webservice
      properties:
        image: springcloud/eureka
        port: 8761
        livenessProbe:
          initialDelaySeconds: 120
          tcpSocket: 
            port: 8761
        redinessProbe:
          initialDelaySeconds: 60
          tcpSocket: 
            port: 8761
      traits:
        - type: expose
          properties:
            port: 8888
