apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: mysql
  namespace: default
spec:
  components:
    - name: config-server
      type: worker
      properties:
        image: springcloud/configserver
        livenessProbe:
          tcpSocket: 
            port: 8888
        redinessProbe:
          tcpSocket: 
            port: 8888
    - name: eureka-server
      type: worker
      properties:
        image: springcloud/eureka
        livenessProbe:
          tcpSocket: 
            port: 8761
        redinessProbe:
          tcpSocket: 
            port: 8761

