apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: mysql
  namespace: default
spec:
  components:
    - name: config-server
      type: helm
      properties:
        repoType: helm
        url: https://kiwigrid.github.io/charts
        chart: spring-cloud-config-server
        version: "0.1.3"
    - name: eureka-server
      type: helm
      properties:
        repoType: helm
        url: https://ygqygq2.github.io/charts
        chart: eureka
        version: "1.0.0"
