apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: my-app
  namespace: default
spec:
  components:
    - name: my-server
      type: webservice
      properties:
        image: ghcr.io/fogdong/test-fog:master-8a4cf881-1633951858
        port: 8088
        env:
          - name: DB_HOST
            value: mysql:3306
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: ROOT_PASSWORD
      traits:
        - type: ingress
          properties:
            domain: demo.c728add480b7640da8dc138ee6e14db0c.cn-hongkong.alicontainer.com
            http:
              /: 8088

  workflow:
    steps:
      - name: apply-server
        type: apply-component
        properties: 
          component: my-server
        outputs:
          - name: server-status
            valueFrom: output.spec.template.spec.containers[0].image + " image applied."